@general_node = @gcse_mm.nodes.create!(label: 'General', position: 'r', topic_area: @general)
@proof_node = @general_node.child_nodes.create!(label: 'Proof')

@number_node = @gcse_mm.nodes.create!(label: 'Number', position: 'r')
@square_root_node = @number_node.child_nodes.create!(label: 'Square Root')
@indices_node = @number_node.child_nodes.create!(label: 'Indices')
@fractions_node = @number_node.child_nodes.create!(label: 'Fractions')
@long_division_node = @number_node.child_nodes.create!(label: 'Long Division')

@algebra_node = @gcse_mm.nodes.create!(label: 'Algebra', position: 'r', topic_area: @pure)
@equations_formulae_node = @algebra_node.child_nodes.create!(label: 'Equations & Formulae')
@identity_node = @equations_formulae_node.child_nodes.create!(label: 'Identity')
@sequences_node = @algebra_node.child_nodes.create!(label: 'Sequences')
@functions_node = @algebra_node.child_nodes.create!(label: 'Functions')
@graphs_node = @algebra_node.child_nodes.create!(label: 'Graphs')

@geometry_measure_node = @gcse_mm.nodes.create!(label: 'Geometry & Measure', position: 'r', topic_area: @geometry)
@rotation_node = @geometry_measure_node.child_nodes.create!(label: 'Rotation')
@pythagoras_node = @geometry_measure_node.child_nodes.create!(label: 'Pythagoras')
@circles_node = @geometry_measure_node.child_nodes.create!(label: 'Circles')
@circle_theorems_node = @circles_node.child_nodes.create!(label: 'Circle Theorems')
@circle_measure_node = @circles_node.child_nodes.create!(label: 'Circle Measure')
@trigonometry_node = @geometry_measure_node.child_nodes.create!(label: 'Trigonometry')
@measurement_node = @geometry_measure_node.child_nodes.create!(label: 'Measurement')
@area_node = @geometry_measure_node.child_nodes.create!(label: 'Area')

@statistics_node = @gcse_mm.nodes.create!(label: 'Statistics', position: 'r', topic_area: @statistics)
@diagrams_node = @statistics_node.child_nodes.create!(label: 'Diagrams')
@summary_statistics_node = @statistics_node.child_nodes.create!(label: 'Summary Statistics')
@sampling_data_node = @statistics_node.child_nodes.create!(label: 'Sampling Data')
@probability_node = @statistics_node.child_nodes.create!(label: 'Probability')
