m_a2_u3_branch = @a_level_maths_mind_map.branches.create!(name: 'M A2 U3', label: 'A2 Unit 3: Pure Mathematics B', topic_area: @pure, position: 'r')

m2_3_1_branch = m_a2_u3_branch.child_branches.create!(name: 'M2.3.1', label: 'M2.3.1 Proof')
m2_3_1_branch.child_branches.create!(name: 'M2.3.1a', label: 'M2.3.1a Proof by Contradiction')

m2_3_2_branch = m_a2_u3_branch.child_branches.create!(name: 'M2.3.2', label: 'M2.3.2 Algebra and Functions')
m2_3_2_branch.child_branches.create!(name: 'M2.3.2a', label: 'M2.3.2a Simplify Rational Expressions')
m2_3_2_branch.child_branches.create!(name: 'M2.3.2b', label: 'M2.3.2b Modulus Function')
m2_3_2_branch.child_branches.create!(name: 'M2.3.2c', label: 'M2.3.2c The Language of Functions')
m2_3_2_branch.child_branches.create!(name: 'M2.3.2d', label: 'M2.3.2d The Combinations of Transformations')
m2_3_2_branch.child_branches.create!(name: 'M2.3.2e', label: 'M2.3.2e Partial Fractions')
m2_3_2_branch.child_branches.create!(name: 'M2.3.2f', label: 'M2.3.2f Functions in Modelling')

m2_3_3_branch = m_a2_u3_branch.child_branches.create!(name: 'M2.3.3', label: 'M2.3.3 Coordinate geometry in the (x,y) plane')
m2_3_3_branch.child_branches.create!(name: 'M2.3.3a', label: 'M2.3.3a Parametric Equations')

m2_3_4_branch = m_a2_u3_branch.child_branches.create!(name: 'M2.3.4', label: 'M2.3.4 Sequences and Series')
m2_3_4_branch.child_branches.create!(name: 'M2.3.4a', label: 'M2.3.4a Binomial expansion for any rational n')
m2_3_4_branch.child_branches.create!(name: 'M2.3.4b', label: 'M2.3.4b Arithmetic Series')
m2_3_4_branch.child_branches.create!(name: 'M2.3.4c', label: 'M2.3.4c Geometric Series')
m2_3_4_branch.child_branches.create!(name: 'M2.3.4d', label: 'M2.3.4d Series in Modelling')

m2_3_5_branch = m_a2_u3_branch.child_branches.create!(name: 'M2.3.5', label: 'M2.3.5 Trigonometry')
m2_3_5_branch.child_branches.create!(name: 'M2.3.5a', label: 'M2.3.5a Radians')
m2_3_5_branch.child_branches.create!(name: 'M2.3.5b', label: 'M2.3.5b Trigonometric functions, inverse, identities and equations')
m2_3_5_branch.child_branches.create!(name: 'M2.3.5c', label: 'M2.3.5c Compound angle formulae')
m2_3_5_branch.child_branches.create!(name: 'M2.3.5d', label: 'M2.3.5d Harmonic form')

m2_3_6_branch = m_a2_u3_branch.child_branches.create!(name: 'M2.3.6', label: 'M2.3.6 Differentiation')
m2_3_6_branch.child_branches.create!(name: 'M2.3.6a', label: 'M2.3.6a Integration')
m2_3_6_branch.child_branches.create!(name: 'M2.3.6b', label: 'M2.3.6b The chain, product & quotient Rule')
m2_3_6_branch.child_branches.create!(name: 'M2.3.6c', label: 'M2.3.6c Differentation of standard functions')
m2_3_6_branch.child_branches.create!(name: 'M2.3.6d', label: 'M2.3.6d Implicit Differentiation')
m2_3_6_branch.child_branches.create!(name: 'M2.3.6e', label: 'M2.3.6e Parametric Differentiation')
m2_3_6_branch.child_branches.create!(name: 'M2.3.6f', label: 'M2.3.6f Differential Equations')

m2_3_7_branch = m_a2_u3_branch.child_branches.create!(name: 'M2.3.7', label: 'M2.3.7 Integration')
m2_3_7_branch.child_branches.create!(name: 'M2.3.7a', label: 'M2.3.7a Integration of further functions')
m2_3_7_branch.child_branches.create!(name: 'M2.3.7b', label: 'M2.3.7b Further Areas')
m2_3_7_branch.child_branches.create!(name: 'M2.3.7c', label: 'M2.3.7c Integrals as limits')
m2_3_7_branch.child_branches.create!(name: 'M2.3.7d', label: 'M2.3.7d Integration by Substitution & by Parts')
m2_3_7_branch.child_branches.create!(name: 'M2.3.7e', label: 'M2.3.7e Using Partial Fractions')
m2_3_7_branch.child_branches.create!(name: 'M2.3.7f', label: 'M2.3.7f Simple Differential Equations')

m2_3_8_branch = m_a2_u3_branch.child_branches.create!(name: 'M2.3.8', label: 'M2.3.8 Numerical Methods')
m2_3_8_branch.child_branches.create!(name: 'M2.3.8a', label: 'M2.3.8a Roots of f(x)=0 and Sign Change Methods')
m2_3_8_branch.child_branches.create!(name: 'M2.3.8b', label: 'M2.3.8b Iteration and Newton Raphson')
m2_3_8_branch.child_branches.create!(name: 'M2.3.8c', label: 'M2.3.8c Definite Integrals & the Trapezium Rule')
