create_link(@proof_branch, 'M2.2.1a', 'simple proofs; nature of proof')

create_link(@square_root_branch, 'FM2.1.2a', "'non-existence' of √(-1)")
create_link(@indices_branch, 'M2.1.2a', 'integer exponents')
create_link(@indices_branch, 'M2.1.6a', 'laws of indices')
create_link(@fractions_branch, 'M2.3.4c', 'recurring fractions')
create_link(@fractions_branch, 'M2.1.7b', 'Four operations with fractions')
create_link(@long_division_branch, 'M2.1.2d', 'traditional method')

create_link(@equations_formulae_branch, 'M2.1.2b', 'quadratics; multiply brackets; simultaneous equations')
create_link(@equations_formulae_branch, 'M2.1.2a', 'difference of 2 squares')
create_link(@equations_formulae_branch, 'M2.1.4a', 'multiply brackets')
create_link(@equations_formulae_branch, 'FM2.3.1a', 'simultaneous equations')
create_link(@equations_formulae_branch, 'M2.1.7a', 'collecting terms; expanding brackets')
create_link(@equations_formulae_branch, 'M2.1.7b', 'collecting terms; expanding brackets')
create_link(@equations_formulae_branch, 'M2.1.7d', 'linear equations; forming equations')
create_link(@identity_branch, 'M2.1.2d', 'comparing coefficients')
create_link(@sequences_branch, 'M2.3.4b', 'linear sequences')
create_link(@functions_branch, 'M2.3.2c', 'notion of inverse')
create_link(@functions_branch, 'M2.1.6b', 'notion of inverse')
create_link(@graphs_branch, 'M2.1.2e', 'transformations; proportion graphs')
create_link(@graphs_branch, 'M2.3.2b', 'graphing y=mx+c')
create_link(@graphs_branch, 'M2.1.6a', 'y=k^x')

create_link(@rotation_branch, 'M2.1.3a', 'perpendicular gradients')
create_link(@pythagoras_branch, 'M2.1.3a', 'distance')
create_link(@pythagoras_branch, 'M2.1.3b', 'construction of equation')
create_link(@pythagoras_branch, 'M2.1.5b', 'theorem Pythagorean triples')
create_link(@pythagoras_branch, 'M2.1.5d', 'theorem')
create_link(@pythagoras_branch, 'M2.1.9a', 'finding magnitude')
create_link(@pythagoras_branch, 'M2.4.4a', 'Pythagorean triples')
create_link(@pythagoras_branch, 'M2.2.9a', 'theorem')
create_link(@circle_theorems_branch, 'M2.1.3b', 'knowledge of')
create_link(@circle_measure_branch, 'M2.3.5a', 'area & circumference')
create_link(@trigonometry_branch, 'M2.1.5a', 'SOHCAHTOA')
create_link(@trigonometry_branch, 'M2.1.5b', 'SOHCAHTOA; Trig graphs; Sine rule; Cosine rule; Area of triangle (using sin)')
create_link(@trigonometry_branch, 'M2.1.9a', 'finding direction')
create_link(@trigonometry_branch, 'M2.2.9a', 'SOHCAHTOA')
create_link(@measurement_branch, 'M2.2.6a', 'basic measures')
create_link(@measurement_branch, 'M2.2.7a', 'av. speed = dist/time; d-t & v-t graphs')
create_link(@measurement_branch, 'M2.2.7b', 'speed = distance / time')
create_link(@area_branch, 'M2.3.8c', 'area of trapezium')

create_link(@diagrams_branch, 'M2.2.2a', 'Histograms; Box & Whisker; cumulative frequency diagrams; types of correlation')
create_link(@summary_statistics_branch, 'M2.1.3a', 'midpoint')
create_link(@summary_statistics_branch, 'M2.2.2b', 'Mean, Median & Mode; Range, IQR')
create_link(@sampling_data_branch, 'M2.2.1a', 'population; sample; discrete or continuous quantitative data; sampling methods')
create_link(@sampling_data_branch, 'M2.2.4a', 'discrete/continuous')
create_link(@probability_branch, 'M2.2.3', 'simple probability; Basic Venn diagrams; Tree diagrams')
