create_link('M2.1.1a', 'M2.1.6b', 'deduction')
create_link('M2.1.1a', 'M2.1.3a', 'development of proof')

create_link('M2.1.2a', 'M2.3.1a', 'irrationality of surds')
create_link('M2.1.2a', 'FM2.1.2a', 'Rationalise the denominator')
create_link('M2.1.2a', 'M2.1.2b', 'exact roots')
create_link('M2.1.2a', 'M2.1.3a', 'exact distances')
create_link('M2.1.2a', 'M2.1.8b', 'roots & reciprocals')
create_link('M2.1.2a', 'M2.1.7b', 'roots & reciprocals')

create_link('M2.1.2b', 'FM2.1.2a', 'solving quadratics')
create_link('M2.1.2b', 'FM2.1.4a', 'identity: comparing coefficients; relationship between coefficients & roots')
create_link('M2.1.2b', 'M2.3.2a', 'factorising expressions')
create_link('M2.1.2b', 'FM2.1.2a', 'quadratics')
create_link('M2.1.2b', 'M2.1.2c', 'quadratics inequalities')
create_link('M2.1.2b', 'M2.1.2d', 'manipulation skills; simple polynomials')
create_link('M2.1.2b', 'M2.1.2e', 'important function')
create_link('M2.1.2b', 'M2.1.3a', 'simultaneous equations')
create_link('M2.1.2b', 'M2.1.3b', 'completing the square; solving line & curve')
create_link('M2.1.2b', 'M2.1.7d', 'solve quadratics')
create_link('M2.1.2b', 'M2.1.8c', 'simultaneous equations')
create_link('M2.1.2b', 'M2.2.7b', 'solving s=ut+(1/2)at^2')
create_link('M2.1.2b', 'M2.3.8a', 'solve; sketch identify sign chance')
create_link('M2.1.2b', 'FM2.4.8b', 'auxiliary equation')
create_link('M2.1.2b', 'M2.3.7b', 'simultaneous equations')
create_link('M2.1.2b', 'M2.1.5', 'trigonometric quadratics')
create_link('M2.1.2b', 'M2.3.2f', 'quadratic models')
create_link('M2.1.2b', 'M2.3.5b', 'quadratics')

create_link('M2.1.2d', '', '')
create_link('M2.1.2d', '', '')
create_link('M2.1.2d', '', '')
create_link('M2.1.2d', '', '')
create_link('M2.1.2d', '', '')
